openapi: 3.0.3
info:
  title: Payment Service API
  version: 1.0.0
  description: API for managing payments

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /payments:
    post:
      summary: Create a new payment
      operationId: createPayment
      tags:
        - payments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentRequest'
      responses:
        '201':
          description: Payment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Bad request - validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreatePaymentRequest:
      type: object
      required:
        - amount
        - currency
        - method
        - userId
      properties:
        amount:
          type: number
          format: double
          minimum: 0.01
          description: Payment amount (must be greater than 0)
          example: 99.99
        currency:
          type: string
          minLength: 1
          description: Currency code (ISO 4217 format)
          example: USD
        method:
          type: string
          enum:
            - CREDIT_CARD
            - DEBIT_CARD
            - PAYPAL
            - BANK_TRANSFER
          description: Payment method
          example: CREDIT_CARD
        userId:
          type: string
          minLength: 1
          description: User identifier
          example: user123
        orderId:
          type: string
          nullable: true
          description: Optional order identifier
          example: order456

    PaymentResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique payment identifier
          example: 1
        amount:
          type: number
          format: double
          description: Payment amount
          example: 99.99
        currency:
          type: string
          description: Currency code
          example: USD
        method:
          type: string
          description: Payment method
          example: CREDIT_CARD
        status:
          type: string
          enum:
            - PENDING
            - APPROVED
            - FAILED
            - CANCELED
          description: Payment status
          example: PENDING
        userId:
          type: string
          description: User identifier
          example: user123
        orderId:
          type: string
          nullable: true
          description: Order identifier
          example: order456
        createdAt:
          type: string
          format: date-time
          description: Payment creation timestamp
          example: 2024-01-15T10:30:00Z
        updatedAt:
          type: string
          format: date-time
          description: Payment last update timestamp
          example: 2024-01-15T10:30:00Z

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: HTTP status code
          example: 400
        message:
          type: string
          description: Error message
          example: Validation failed
        details:
          type: string
          description: Additional error details
          example: Amount must be greater than 0

